apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mydb56
  description: New Valkey db cluster named mydb56
  annotations:
    github.com/project-slug: test-backstage6/mydb56
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://dashboard.example.com
      title: Grafana dashboard for mydb56
      icon: dashboard
spec:
  type: service
  owner: development
  lifecycle: experimental
