apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mydb13
  description: New Valkey db cluster named mydb13
  annotations:
    github.com/project-slug: test-backstage6/mydb13
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://dashboard.example.com
      title: Grafana dashboard for mydb13
      icon: dashboard
spec:
  type: service
  owner: development
  lifecycle: experimental
